#!/usr/bin/env bash
# =============================================================================
# run_mdpocket_char.sh  —  SLURM worker script
#
# Runs mdpocket characterization for a single sequence using the
# selected_pocket.pdb generated by select_binding_pocket.py.
#
# Called by submit_mdpocket_char.sh:
#   sbatch run_mdpocket_char.sh <seq_id> <dir_type> [overwrite] [suffix]
#
# overwrite ("true"/"false", default false) forces mdpocket characterization
# to rerun and removes the existing descriptors file first, instead of
# skipping when it already exists. Needed after a stale input gets fixed
# upstream (e.g. a PetaLibrary archive resync).
#
# suffix - run-directory suffix, e.g. "_qfix" (default: "")
# =============================================================================

#SBATCH --job-name=mdpocket_char
#SBATCH --output=/projects/ivta1597/biosensors/pkt_vol/logs/mdpocket_char_%j.out
#SBATCH --error=/projects/ivta1597/biosensors/pkt_vol/logs/mdpocket_char_%j.err
#SBATCH --account=ucb351_asc4
#SBATCH --partition=acpu
#SBATCH --time=20:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --constraint=ib
#SBATCH --qos=cpu-normal
#SBATCH --mail-user=ivana.tang@colorado.edu
#SBATCH --mail-type=BEGIN,END,FAIL

export TMPDIR=$SLURM_SCRATCH
export SLURM_EXPORT_ENV=ALL

module purge
module load gcc
module load openmpi
module load anaconda
conda activate fpocket_env

# ── Configurable paths ────────────────────────────────────────────────────────
# INPUT_XTC/REF_PDB/SELECTED_POCKET are normally scratch-only pipeline
# artifacts (from pkt_vol_prep.sh and select_binding_pocket.py), but for
# sequences processed a while ago they can themselves have aged out of
# scratch's 90-day window. Fall back to the PetaLibrary archive if missing
# from scratch. mdpocket has a known malloc crash on long path arguments, so
# (as before) we cd into RUN_DIR and reference bare filenames -- any file
# resolved from the archive is copied into RUN_DIR first rather than passed
# as a long absolute archive path.
ARCHIVE_BASE="/pl/active/shirts_archive/IvanaTang/biosensors"
BASE="/scratch/alpine/ivta1597/LCA_boltz_models"
RUNREL="prod_md_0p9_cutoff_3dt_64x1_16PME_642dd"
INPUT_XTC="protein_only.xtc"
REF_PDB="protein_only.pdb"
SELECTED_POCKET="selected_pocket.pdb"
# ─────────────────────────────────────────────────────────────────────────────

SEQ_ID=$1
DIR_TYPE=$2
OVERWRITE=${3:-false}
SUFFIX=${4:-}
RUNREL="${RUNREL}${SUFFIX}"

if [[ -z "$SEQ_ID" || -z "$DIR_TYPE" ]]; then
    echo "ERROR: usage: sbatch run_mdpocket_char.sh <seq_id> <dir_type> [overwrite] [suffix]"
    exit 1
fi

RUN_DIR="${BASE}/${DIR_TYPE}/${SEQ_ID}/${RUNREL}"
ARCHIVE_FLAT_DIR="${ARCHIVE_BASE}/${DIR_TYPE}/${SEQ_ID}/${RUNREL}"
ARCHIVE_NESTED_DIR="${ARCHIVE_FLAT_DIR}/500ns"
DESCRIPTORS="${RUN_DIR}/mdpocket_${SEQ_ID}_descriptors.txt"

echo "seq_id   : $SEQ_ID"
echo "dir_type : $DIR_TYPE"
echo "run_dir  : $RUN_DIR"
echo ""

# If missing from scratch, copy in from the archive (flat then runrel/500ns/)
# so mdpocket can still reference it as a short, bare filename.
stage_file() {
    local filename="$1"
    if [[ -f "${RUN_DIR}/${filename}" ]]; then
        return 0
    fi
    for d in "$ARCHIVE_FLAT_DIR" "$ARCHIVE_NESTED_DIR"; do
        if [[ -f "${d}/${filename}" ]]; then
            mkdir -p "$RUN_DIR"
            cp "${d}/${filename}" "${RUN_DIR}/${filename}"
            echo "  Staged from archive: ${d}/${filename} -> ${RUN_DIR}/${filename}"
            return 0
        fi
    done
    return 1
}

# ── Validate/stage inputs ──────────────────────────────────────────────────────
abort=0
for f in "$INPUT_XTC" "$REF_PDB" "$SELECTED_POCKET"; do
    if ! stage_file "$f"; then
        echo "ERROR: $f not found in $RUN_DIR, $ARCHIVE_FLAT_DIR, or $ARCHIVE_NESTED_DIR"
        abort=1
    fi
done
if [[ $abort -eq 1 ]]; then
    exit 1
fi

# ── Skip if descriptors already exist, unless overwriting ─────────────────────
if [[ "$OVERWRITE" == "true" ]]; then
    echo "OVERWRITE: removing existing descriptors"
    rm -f "$DESCRIPTORS"
elif [[ -f "$DESCRIPTORS" ]]; then
    echo "SKIP: descriptors already exist: $DESCRIPTORS (use --overwrite-existing to regenerate)"
    exit 0
fi

# ── Run mdpocket characterization ─────────────────────────────────────────────
# cd into run directory — avoids malloc crash from long path lengths (fpocket bug)
echo "Running mdpocket characterization..."
cd "$RUN_DIR"

mdpocket \
    --trajectory_file   "$INPUT_XTC"      \
    --trajectory_format xtc               \
    --selected_pocket   "$SELECTED_POCKET" \
    -f                  "$REF_PDB"         \
    -o                  "mdpocket_${SEQ_ID}"

EXIT_CODE=$?

if [[ $EXIT_CODE -eq 0 && -f "$DESCRIPTORS" ]]; then
    echo ""
    echo "OK: $DESCRIPTORS"
    wc -l "$DESCRIPTORS"
else
    echo ""
    echo "FAILED: mdpocket exited with code $EXIT_CODE or descriptors file missing"
    exit 1
fi
