#!/usr/bin/env bash
# =============================================================================
# run_mdpocket_char.sh  —  SLURM worker script
#
# Runs mdpocket characterization for a single sequence using the
# selected_pocket.pdb generated by select_binding_pocket.py.
#
# Called by submit_mdpocket_char.sh:
#   sbatch run_mdpocket_char.sh <seq_id> <dir_type>
# =============================================================================

#SBATCH --job-name=mdpocket_char
#SBATCH --output=logs/mdpocket_char_%j.out
#SBATCH --error=logs/mdpocket_char_%j.err
#SBATCH --account=ucb351_asc4
#SBATCH --partition=amilan
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --constraint=ib
#SBATCH --qos=normal
#SBATCH --mail-user=ivana.tang@colorado.edu
#SBATCH --mail-type=BEGIN,END,FAIL

export TMPDIR=$SLURM_SCRATCH
export SLURM_EXPORT_ENV=ALL

module purge
module load gcc
module load openmpi
module load anaconda
conda activate fpocket_env

# ── Configurable paths ────────────────────────────────────────────────────────
BASE="/scratch/alpine/ivta1597/LCA_boltz_models"
RUNREL="prod_md_0p9_cutoff_3dt_64x1_16PME_642dd"
INPUT_XTC="protein_only.xtc"
REF_PDB="protein_only.pdb"
SELECTED_POCKET="selected_pocket.pdb"
# ─────────────────────────────────────────────────────────────────────────────

SEQ_ID=$1
DIR_TYPE=$2

if [[ -z "$SEQ_ID" || -z "$DIR_TYPE" ]]; then
    echo "ERROR: usage: sbatch run_mdpocket_char.sh <seq_id> <dir_type>"
    exit 1
fi

RUN_DIR="${BASE}/${DIR_TYPE}/${SEQ_ID}/${RUNREL}"
DESCRIPTORS="${RUN_DIR}/mdpocket_${SEQ_ID}_descriptors.txt"

echo "seq_id   : $SEQ_ID"
echo "dir_type : $DIR_TYPE"
echo "run_dir  : $RUN_DIR"
echo ""

# ── Validate inputs ───────────────────────────────────────────────────────────
if [[ ! -d "$RUN_DIR" ]]; then
    echo "ERROR: run directory not found: $RUN_DIR"; exit 1
fi
for f in "${RUN_DIR}/${INPUT_XTC}" "${RUN_DIR}/${REF_PDB}" "${RUN_DIR}/${SELECTED_POCKET}"; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: required file not found: $f"; exit 1
    fi
done

# ── Skip if descriptors already exist ────────────────────────────────────────
if [[ -f "$DESCRIPTORS" ]]; then
    echo "SKIP: descriptors already exist: $DESCRIPTORS"
    exit 0
fi

# ── Run mdpocket characterization ─────────────────────────────────────────────
# cd into run directory — avoids malloc crash from long path lengths (fpocket bug)
echo "Running mdpocket characterization..."
cd "$RUN_DIR"

mdpocket \
    --trajectory_file   "$INPUT_XTC"      \
    --trajectory_format xtc               \
    --selected_pocket   "$SELECTED_POCKET" \
    -f                  "$REF_PDB"         \
    -o                  "mdpocket_${SEQ_ID}"

EXIT_CODE=$?

if [[ $EXIT_CODE -eq 0 && -f "$DESCRIPTORS" ]]; then
    echo ""
    echo "OK: $DESCRIPTORS"
    wc -l "$DESCRIPTORS"
else
    echo ""
    echo "FAILED: mdpocket exited with code $EXIT_CODE or descriptors file missing"
    exit 1
fi
